### ISSUE TITLE
Error with Tidy - Column 6 must be named

### ISSUE THREAD

**Issue by Move87** [tidymodels/broom#496]
I'm trying to use tidy to put a regression result into table format to export to Excel. My codes worked fine last month, but today I got the Error: Column 6 must be named. I reinstalled R and this package because I got a new PC.  Below is an example:

```r
> CarReg = lm(formula = speed ~., data = cars)
# Standardize coefficients
> library(lm.beta)
> CarRegS = lm.beta::lm.beta(CarReg)
# Table format
> library(broom)
> tidy(CarRegS)
Error: Column 6 must be named
```

**Comment by Move87** [comment]
I just tried version 0.4.5, 0.4.3 and 0.4.1. Only 0.4.1 worked.

**Comment by alexpghayes** [comment]
It looks like this because the `lm.beta` package creates a new `lm.beta` object with its own `summary` method. Since the `lm.beta` object subclasses `lm`, the `lm` tidier kicks in. It looks like this accidentally used to work, but it doesn't anymore.

We could add a tidier for `lm.beta` objects, but it'll be quite a while before I get around to that. If you'd like to see that functionality sooner, I'd encourage you to make a PR!

**Comment by mattle24** [comment]
Hi Alex, I'd like to try to fix this by adding a new tidier for `lm.beta`. Opened a PR [#545](https://github.com/tidymodels/broom/pull/545)

**Comment by mattle24** [comment]
@Move87 the `lm.beta` tidier has been merged

**Comment by ldmahoney** [comment]
Hello, I am using broom version 0.5.3 to try to tidy lm.beta objects. I see this issue was addressed previously but I am having the same problem now. I used the example from the documentation on this function (https://broom.tidyverse.org/reference/tidy.lm.beta.html) and the issue I was having with my own data was replicated. 

`> mod <- stats::lm(speed ~ ., data = cars)
> std <- lm.beta(mod)
> tidy(std)
Error: Column 6 must be named.
Use .name_repair to specify repair.
> `

Thank you to anyone willing to help me with this!

**Comment by mattle24** [comment]
@ldmahoney Hmm, I'm not able to replicate your error. Could you please include your session info in addition to the example you posted? I think the versions of the packages `broom` and `tibble` are probably the most relevant.

Here's what I ran:

```
reprex::reprex({
  library(broom)
  library(lm.beta)
  
  mod <- stats::lm(speed ~ ., data = cars)
  std <- lm.beta(mod)
  tidy(std)
}, si = TRUE)
```

And here's what I got:

``` r
library(broom)
library(lm.beta)

mod <- stats::lm(speed ~ ., data = cars)
std <- lm.beta(mod)
tidy(std)
#> # A tibble: 2 x 6
#>   term        estimate std_estimate std.error statistic  p.value
#>   <chr>          <dbl>        <dbl>     <dbl>     <dbl>    <dbl>
#> 1 (Intercept)    8.28         0        0.874       9.47 1.44e-12
#> 2 dist           0.166        0.807    0.0175      9.46 1.49e-12
```

<sup>Created on 2020-01-17 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

<details>

<summary>Session info</summary>

``` r
devtools::session_info()
#> ─ Session info ───────────────────────────────────────────────────────────────
#>  setting  value                       
#>  version  R version 3.5.2 (2018-12-20)
#>  ui       X11                         
#>  language (EN)                        
#>  collate  en_US.UTF-8                 
#>  ctype    en_US.UTF-8                 
#> 
#> ─ Packages ───────────────────────────────────────────────────────────────────
#>  package     * version    date       lib source                           
#>  assertthat    0.2.1      2019-03-21 [3] CRAN (R 3.5.2)                   
#>  backports     1.1.5      2019-10-02 [1] CRAN (R 3.5.2)                   
#>  broom       * 0.5.3.9000 2020-01-17 [1] Github (tidymodels/broom@3c922d5)
#>  callr         3.4.0      2019-12-09 [2] CRAN (R 3.5.2)                   
#>  cli           2.0.0      2019-12-09 [2] CRAN (R 3.5.2)                   
#>  crayon        1.3.4      2017-09-16 [3] CRAN (R 3.5.0)                   
#>  desc          1.2.0      2018-05-01 [3] CRAN (R 3.5.0)                   
#>  devtools      2.2.1      2019-09-24 [1] CRAN (R 3.5.2)                   
#>  digest        0.6.23     2019-11-23 [1] CRAN (R 3.5.2)                   
#>  dplyr         0.8.3      2019-07-04 [3] CRAN (R 3.5.2)                   
#>  ellipsis      0.3.0      2019-09-20 [2] CRAN (R 3.5.2)                   
#>  evaluate      0.14       2019-05-28 [3] CRAN (R 3.5.2)                   
#>  fansi         0.4.0      2018-10-05 [3] CRAN (R 3.5.0)                   
#>  fs            1.3.1      2019-05-06 [3] CRAN (R 3.5.2)                   
#>  generics      0.0.2      2018-11-29 [1] CRAN (R 3.5.0)                   
#>  glue          1.3.1      2019-03-12 [3] CRAN (R 3.5.2)                   
#>  highr         0.8        2019-03-20 [3] CRAN (R 3.5.2)                   
#>  htmltools     0.4.0      2019-10-04 [1] CRAN (R 3.5.2)                   
#>  knitr         1.26       2019-11-12 [1] CRAN (R 3.5.2)                   
#>  lifecycle     0.1.0      2019-08-01 [1] CRAN (R 3.5.2)                   
#>  lm.beta     * 1.5-1      2014-12-28 [1] CRAN (R 3.5.0)                   
#>  magrittr      1.5        2014-11-22 [3] CRAN (R 3.5.0)                   
#>  memoise       1.1.0      2017-04-21 [3] CRAN (R 3.5.0)                   
#>  pillar        1.4.2      2019-06-29 [3] CRAN (R 3.5.2)                   
#>  pkgbuild      1.0.6      2019-10-09 [2] CRAN (R 3.5.2)                   
#>  pkgconfig     2.0.3      2019-09-22 [2] CRAN (R 3.5.2)                   
#>  pkgload       1.0.2      2018-10-29 [3] CRAN (R 3.5.0)                   
#>  prettyunits   1.0.2      2015-07-13 [3] CRAN (R 3.5.0)                   
#>  processx      3.4.1      2019-07-18 [2] CRAN (R 3.5.2)                   
#>  ps            1.3.0      2018-12-21 [3] CRAN (R 3.5.0)                   
#>  purrr         0.3.3      2019-10-18 [1] CRAN (R 3.5.2)                   
#>  R6            2.4.1      2019-11-12 [2] CRAN (R 3.5.2)                   
#>  Rcpp          1.0.3      2019-11-08 [2] CRAN (R 3.5.2)                   
#>  remotes       2.1.0      2019-06-24 [3] CRAN (R 3.5.2)                   
#>  rlang         0.4.2      2019-11-23 [1] CRAN (R 3.5.2)                   
#>  rmarkdown     1.18       2019-11-27 [1] CRAN (R 3.5.2)                   
#>  rprojroot     1.3-2      2018-01-03 [1] CRAN (R 3.5.0)                   
#>  sessioninfo   1.1.1      2018-11-05 [3] CRAN (R 3.5.0)                   
#>  stringi       1.4.3      2019-03-12 [3] CRAN (R 3.5.2)                   
#>  stringr       1.4.0      2019-02-10 [3] CRAN (R 3.5.2)                   
#>  testthat      2.3.1      2019-12-01 [2] CRAN (R 3.5.2)                   
#>  tibble        2.1.3      2019-06-06 [3] CRAN (R 3.5.2)                   
#>  tidyr         1.0.0      2019-09-11 [1] CRAN (R 3.5.2)                   
#>  tidyselect    0.2.5      2018-10-11 [2] CRAN (R 3.5.0)                   
#>  usethis       1.5.1      2019-07-04 [1] CRAN (R 3.5.2)                   
#>  utf8          1.1.4      2018-05-24 [3] CRAN (R 3.5.0)                   
#>  vctrs         0.2.0      2019-07-05 [3] CRAN (R 3.5.2)                   
#>  withr         2.1.2      2018-03-15 [3] CRAN (R 3.5.0)                   
#>  xfun          0.11       2019-11-12 [1] CRAN (R 3.5.2)                   
#>  yaml          2.2.0      2018-07-25 [3] CRAN (R 3.5.0)                   
#>  zeallot       0.1.0      2018-01-28 [3] CRAN (R 3.5.0)                   
#> 
#> [3] /Library/Frameworks/R.framework/Versions/3.5/Resources/library
```

</details>

**Comment by ldmahoney** [comment]
@mattle24 Thank you for your reply! Below is more information about my error and system

Here's what I ran
``` r
reprex::reprex({
  library(broom)
  library(lm.beta)
  
  mod <- stats::lm(speed ~ ., data = cars)
  std <- lm.beta(mod)
  tidy(std)
}, si = TRUE)
rlang::last_error()
```
And here's what I got as a result. I added the error information in case that helps. It does seem at face value that tidy.lm(std) would throw an error. I would expect to see tidy.lm.beta(std). 
``` r
library(broom)
#> Warning: package 'broom' was built under R version 3.5.3
library(lm.beta)

mod <- stats::lm(speed ~ ., data = cars)
std <- lm.beta(mod)
tidy(std)
#> Error: Column 6 must be named.
#> Use .name_repair to specify repair.
rlang::last_error()
<error/rlang_error>
Column 6 must be named.
Use .name_repair to specify repair.
Backtrace:
  1. generics::tidy(std)
  2. broom:::tidy.lm(std)
  3. broom:::tidy.summary.lm(s)
  4. broom::fix_data_frame(co, nn[1:ncol(co)])
  6. tibble:::as_tibble.data.frame(ret)
  7. tibble:::as_tibble.list(unclass(x), ..., .rows = .rows, .name_repair = .name_repair)
  8. tibble:::lst_to_tibble(x, .rows, .name_repair, col_lengths(x))
  9. tibble:::set_repaired_names(x, .name_repair)
 14. tibble:::repaired_names(names(x), .name_repair = .name_repair)
 15. tibble:::check_unique(new_name)
```
<sup>Created on 2020-01-17 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

<details>

<summary>Session info</summary>

``` r
devtools::session_info()
#> - Session info ---------------------------------------------------------------
#>  setting  value                       
#>  version  R version 3.5.2 (2018-12-20)
#>  os       Windows 10 x64              
#>  system   x86_64, mingw32             
#>  ui       RTerm                       
#>  language (EN)                        
#>  collate  English_United States.1252  
#>  ctype    English_United States.1252  
#>  tz       America/Los_Angeles         
#>  date     2020-01-17                  
#> 
#> - Packages -------------------------------------------------------------------
#>  package     * version date       lib source        
#>  assertthat    0.2.1   2019-03-21 [1] CRAN (R 3.5.3)
#>  backports     1.1.5   2019-10-02 [1] CRAN (R 3.5.3)
#>  broom       * 0.5.3   2019-12-14 [1] CRAN (R 3.5.3)
#>  callr         3.4.0   2019-12-09 [1] CRAN (R 3.5.3)
#>  cli           2.0.1   2020-01-08 [1] CRAN (R 3.5.3)
#>  crayon        1.3.4   2017-09-16 [1] CRAN (R 3.5.3)
#>  desc          1.2.0   2018-05-01 [1] CRAN (R 3.5.3)
#>  devtools      2.2.1   2019-09-24 [1] CRAN (R 3.5.3)
#>  digest        0.6.23  2019-11-23 [1] CRAN (R 3.5.3)
#>  dplyr         0.8.3   2019-07-04 [1] CRAN (R 3.5.3)
#>  ellipsis      0.3.0   2019-09-20 [1] CRAN (R 3.5.3)
#>  evaluate      0.14    2019-05-28 [1] CRAN (R 3.5.3)
#>  fansi         0.4.1   2020-01-08 [1] CRAN (R 3.5.3)
#>  fs            1.3.1   2019-05-06 [1] CRAN (R 3.5.3)
#>  generics      0.0.2   2018-11-29 [1] CRAN (R 3.5.3)
#>  glue          1.3.1   2019-03-12 [1] CRAN (R 3.5.3)
#>  highr         0.8     2019-03-20 [1] CRAN (R 3.5.3)
#>  htmltools     0.4.0   2019-10-04 [1] CRAN (R 3.5.3)
#>  knitr         1.27    2020-01-16 [1] CRAN (R 3.5.2)
#>  lattice       0.20-38 2018-11-04 [2] CRAN (R 3.5.2)
#>  lifecycle     0.1.0   2019-08-01 [1] CRAN (R 3.5.3)
#>  lm.beta     * 1.5-1   2014-12-28 [1] CRAN (R 3.5.2)
#>  magrittr      1.5     2014-11-22 [1] CRAN (R 3.5.3)
#>  memoise       1.1.0   2017-04-21 [1] CRAN (R 3.5.3)
#>  nlme          3.1-137 2018-04-07 [2] CRAN (R 3.5.2)
#>  pillar        1.4.3   2019-12-20 [1] CRAN (R 3.5.3)
#>  pkgbuild      1.0.6   2019-10-09 [1] CRAN (R 3.5.3)
#>  pkgconfig     2.0.3   2019-09-22 [1] CRAN (R 3.5.3)
#>  pkgload       1.0.2   2018-10-29 [1] CRAN (R 3.5.3)
#>  prettyunits   1.1.0   2020-01-09 [1] CRAN (R 3.5.3)
#>  processx      3.4.1   2019-07-18 [1] CRAN (R 3.5.3)
#>  ps            1.3.0   2018-12-21 [1] CRAN (R 3.5.3)
#>  purrr         0.3.3   2019-10-18 [1] CRAN (R 3.5.3)
#>  R6            2.4.1   2019-11-12 [1] CRAN (R 3.5.3)
#>  Rcpp          1.0.3   2019-11-08 [1] CRAN (R 3.5.3)
#>  remotes       2.1.0   2019-06-24 [1] CRAN (R 3.5.3)
#>  rlang         0.4.2   2019-11-23 [1] CRAN (R 3.5.3)
#>  rmarkdown     2.0     2019-12-12 [1] CRAN (R 3.5.3)
#>  rprojroot     1.3-2   2018-01-03 [1] CRAN (R 3.5.3)
#>  sessioninfo   1.1.1   2018-11-05 [1] CRAN (R 3.5.3)
#>  stringi       1.4.5   2020-01-11 [1] CRAN (R 3.5.3)
#>  stringr       1.4.0   2019-02-10 [1] CRAN (R 3.5.3)
#>  testthat      2.3.1   2019-12-01 [1] CRAN (R 3.5.3)
#>  tibble        2.1.3   2019-06-06 [1] CRAN (R 3.5.3)
#>  tidyr         1.0.0   2019-09-11 [1] CRAN (R 3.5.3)
#>  tidyselect    0.2.5   2018-10-11 [1] CRAN (R 3.5.3)
#>  usethis       1.5.1   2019-07-04 [1] CRAN (R 3.5.3)
#>  vctrs         0.2.1   2019-12-17 [1] CRAN (R 3.5.3)
#>  withr         2.1.2   2018-03-15 [1] CRAN (R 3.5.3)
#>  xfun          0.12    2020-01-13 [1] CRAN (R 3.5.3)
#>  yaml          2.2.0   2018-07-25 [1] CRAN (R 3.5.3)
#>  zeallot       0.1.0   2018-01-28 [1] CRAN (R 3.5.3)
#> 
#> [1] C:/Users/I517924/Documents/R/win-library/3.5
#> [2] C:/Program Files/R/R-3.5.2/library
```

</details>

**Comment by mattle24** [comment]
@ldmahoney Thanks so much for the great reproducible example and the error traceback! I was hoping something would pop out, but I'm still not sure what the issue is.

I haven't been contributing to broom for a while so I don't want to speak for the maintainers, but I think the best thing to do would be to file a new issue to get attention to your issue.

**Comment by ldmahoney** [comment]
I appreciate you taking a look at this for me, Matt! I open an issue and
see what comes of that :).

-Luke

**Comment by BramNitert** [comment]
I had the same issue after I started a new R session (but with tidy on a lmer function instead of your lm.beta). Probably because of delayed loading of broom tools. After it loaded (after +- 5 minutes) it worked as when I wrote the script.
Hope that helps!

**Comment by pmeiners** [comment]
> I had the same issue after I started a new R session (but with tidy on a lmer function instead of your lm.beta). Probably because of delayed loading of broom tools. After it loaded (after +- 5 minutes) it worked as when I wrote the script.
> Hope that helps!

I had the same issue. Loading "broom.mixed" as the last package helped. Its possible that some other package used a different tidier.
